# Generated by Django 4.0.7 on 2023-07-12 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sector', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha Contratación')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('redes', models.URLField(blank=True, verbose_name='Redes Sociales')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('tipoEvento', models.CharField(max_length=40, verbose_name='Tipo Evento')),
                ('privado', models.BooleanField(verbose_name='Evento Privado (privado ✔ / semiprivado ✘)')),
                ('fechaSolicitud', models.DateTimeField(verbose_name='Fecha Solicitud')),
                ('fechaEvento', models.DateTimeField(verbose_name='Fecha Evento')),
                ('horaEvento', models.TimeField(null=True, verbose_name='Hora Evento')),
                ('numeroInvitados', models.IntegerField(validators=[django.core.validators.MaxValueValidator(115)], verbose_name='Número Invitados (máx 115)')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (opcional)')),
                ('duracion', models.IntegerField(verbose_name='Duración (horas)')),
                ('costo', models.IntegerField(blank=True, verbose_name='Costo: (opcional)')),
                ('estado', models.BooleanField(verbose_name='Estado (activo ✔ / inactivo ✘)')),
                ('anotaciones', models.TextField(blank=True, verbose_name='Anotaciones (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='ReservasMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('fechaReserva', models.DateTimeField(verbose_name='Fecha Reserva')),
                ('horaReserva', models.TimeField(verbose_name='Hora Reserva')),
                ('numeroPersonas', models.IntegerField(verbose_name='Número Personas')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (opcional)')),
                ('estado', models.BooleanField(verbose_name='Estado: (activo ✔ / inactivo ✘)')),
                ('anotaciones', models.TextField(blank=True, verbose_name='Anotaciones (Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('sector', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('fechaContratacion', models.DateField(verbose_name='Fecha Contratación')),
                ('salario', models.IntegerField()),
                ('foto_id', models.ImageField(blank=True, upload_to='fotos_id')),
                ('anotaciones', models.TextField(blank=True, verbose_name='Anotaciones (opcionales)')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='blog_files/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
